# Generated by Django 4.1.5 on 2023-01-06 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id_kota', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kota', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Distrik',
            fields=[
                ('id_distrik', models.AutoField(primary_key=True, serialize=False)),
                ('nama_distrik', models.CharField(max_length=30)),
                ('kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.kota')),
            ],
        ),
    ]
